export enum ProductCategory {
  ELECTRONICS = 'ELECTRONICS',
  CLOTHING = 'CLOTHING',
  BOOKS = 'BOOKS',
  HOME_APPLIANCES = 'HOME_APPLIANCES',
  TOYS = 'TOYS',
  BEAUTY = 'BEAUTY',
  SPORTS = 'SPORTS',
  GROCERIES = 'GROCERIES',
  FURNITURE = 'FURNITURE',
  AUTOMOTIVE = 'AUTOMOTIVE',
  JEWELRY = 'JEWELRY',
  OFFICE_SUPPLIES = 'OFFICE_SUPPLIES',
  HEALTH = 'HEALTH',
  PET_SUPPLIES = 'PET_SUPPLIES',
  GARDEN = 'GARDEN'
}
